# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

average_xy_2D_r_cpp <- function(input_xyv, range_x, range_y) {
    .Call(`_dtRtools_average_xy_2D_r_cpp`, input_xyv, range_x, range_y)
}

average_2D_2D_r_cpp <- function(input_x, input_y, input_2D, range_x, range_y) {
    .Call(`_dtRtools_average_2D_2D_r_cpp`, input_x, input_y, input_2D, range_x, range_y)
}

average_grid_t <- function(input_xy, input_2Dt, input_t, xyout, outx, outy, out_t) {
    .Call(`_dtRtools_average_grid_t`, input_xy, input_2Dt, input_t, xyout, outx, outy, out_t)
}

interpolate_2D_xy_cpp <- function(input_x, input_y, input_2D, output_xy, asp) {
    .Call(`_dtRtools_interpolate_2D_xy_cpp`, input_x, input_y, input_2D, output_xy, asp)
}

interpolate_2D_xy_r_cpp <- function(range_x, range_y, input_2D, output_xy, asp) {
    .Call(`_dtRtools_interpolate_2D_xy_r_cpp`, range_x, range_y, input_2D, output_xy, asp)
}

interpolate_xy_2D_cpp <- function(input_xyv, output_x, output_y, nmean, max_distance, asp) {
    .Call(`_dtRtools_interpolate_xy_2D_cpp`, input_xyv, output_x, output_y, nmean, max_distance, asp)
}

interpolate_2D_2D_cpp <- function(input_x, input_y, input_2D, output_x, output_y, asp) {
    .Call(`_dtRtools_interpolate_2D_2D_cpp`, input_x, input_y, input_2D, output_x, output_y, asp)
}

interpolate_2D_2D_r_cpp <- function(range_x, range_y, input_2D, output_x, output_y, asp) {
    .Call(`_dtRtools_interpolate_2D_2D_r_cpp`, range_x, range_y, input_2D, output_x, output_y, asp)
}

interpolate_xy_xy_cpp <- function(input_xyv, output_xy, nmean, max_distance, asp) {
    .Call(`_dtRtools_interpolate_xy_xy_cpp`, input_xyv, output_xy, nmean, max_distance, asp)
}

interpolate_ts_cpp <- function(input_xy, input_t, output_xy, nmean, asp) {
    .Call(`_dtRtools_interpolate_ts_cpp`, input_xy, input_t, output_xy, nmean, asp)
}

interpolate_ts_xy_2D_cpp <- function(input_xy, input_t, output_x, output_y, nmean, asp) {
    .Call(`_dtRtools_interpolate_ts_xy_2D_cpp`, input_xy, input_t, output_x, output_y, nmean, asp)
}

