// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// average_xy_2D_r_cpp
NumericMatrix average_xy_2D_r_cpp(NumericMatrix input_xyv, NumericVector range_x, NumericVector range_y);
RcppExport SEXP _dtRtools_average_xy_2D_r_cpp(SEXP input_xyvSEXP, SEXP range_xSEXP, SEXP range_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type input_xyv(input_xyvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type range_x(range_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type range_y(range_ySEXP);
    rcpp_result_gen = Rcpp::wrap(average_xy_2D_r_cpp(input_xyv, range_x, range_y));
    return rcpp_result_gen;
END_RCPP
}
// average_2D_2D_r_cpp
NumericMatrix average_2D_2D_r_cpp(NumericVector input_x, NumericVector input_y, NumericMatrix input_2D, NumericVector range_x, NumericVector range_y);
RcppExport SEXP _dtRtools_average_2D_2D_r_cpp(SEXP input_xSEXP, SEXP input_ySEXP, SEXP input_2DSEXP, SEXP range_xSEXP, SEXP range_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type input_x(input_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type input_y(input_ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type input_2D(input_2DSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type range_x(range_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type range_y(range_ySEXP);
    rcpp_result_gen = Rcpp::wrap(average_2D_2D_r_cpp(input_x, input_y, input_2D, range_x, range_y));
    return rcpp_result_gen;
END_RCPP
}
// average_grid_t
NumericMatrix average_grid_t(NumericMatrix input_xy, NumericMatrix input_2Dt, NumericVector input_t, NumericMatrix xyout, NumericVector outx, NumericVector outy, NumericVector out_t);
RcppExport SEXP _dtRtools_average_grid_t(SEXP input_xySEXP, SEXP input_2DtSEXP, SEXP input_tSEXP, SEXP xyoutSEXP, SEXP outxSEXP, SEXP outySEXP, SEXP out_tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type input_xy(input_xySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type input_2Dt(input_2DtSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type input_t(input_tSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type xyout(xyoutSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type outx(outxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type outy(outySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type out_t(out_tSEXP);
    rcpp_result_gen = Rcpp::wrap(average_grid_t(input_xy, input_2Dt, input_t, xyout, outx, outy, out_t));
    return rcpp_result_gen;
END_RCPP
}
// interpolate_2D_xy_cpp
NumericVector interpolate_2D_xy_cpp(NumericVector input_x, NumericVector input_y, NumericMatrix input_2D, NumericMatrix output_xy, double asp);
RcppExport SEXP _dtRtools_interpolate_2D_xy_cpp(SEXP input_xSEXP, SEXP input_ySEXP, SEXP input_2DSEXP, SEXP output_xySEXP, SEXP aspSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type input_x(input_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type input_y(input_ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type input_2D(input_2DSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type output_xy(output_xySEXP);
    Rcpp::traits::input_parameter< double >::type asp(aspSEXP);
    rcpp_result_gen = Rcpp::wrap(interpolate_2D_xy_cpp(input_x, input_y, input_2D, output_xy, asp));
    return rcpp_result_gen;
END_RCPP
}
// interpolate_2D_xy_r_cpp
NumericVector interpolate_2D_xy_r_cpp(NumericVector range_x, NumericVector range_y, NumericMatrix input_2D, NumericMatrix output_xy, double asp);
RcppExport SEXP _dtRtools_interpolate_2D_xy_r_cpp(SEXP range_xSEXP, SEXP range_ySEXP, SEXP input_2DSEXP, SEXP output_xySEXP, SEXP aspSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type range_x(range_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type range_y(range_ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type input_2D(input_2DSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type output_xy(output_xySEXP);
    Rcpp::traits::input_parameter< double >::type asp(aspSEXP);
    rcpp_result_gen = Rcpp::wrap(interpolate_2D_xy_r_cpp(range_x, range_y, input_2D, output_xy, asp));
    return rcpp_result_gen;
END_RCPP
}
// interpolate_xy_2D_cpp
NumericMatrix interpolate_xy_2D_cpp(NumericMatrix input_xyv, NumericVector output_x, NumericVector output_y, int nmean, double asp);
RcppExport SEXP _dtRtools_interpolate_xy_2D_cpp(SEXP input_xyvSEXP, SEXP output_xSEXP, SEXP output_ySEXP, SEXP nmeanSEXP, SEXP aspSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type input_xyv(input_xyvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type output_x(output_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type output_y(output_ySEXP);
    Rcpp::traits::input_parameter< int >::type nmean(nmeanSEXP);
    Rcpp::traits::input_parameter< double >::type asp(aspSEXP);
    rcpp_result_gen = Rcpp::wrap(interpolate_xy_2D_cpp(input_xyv, output_x, output_y, nmean, asp));
    return rcpp_result_gen;
END_RCPP
}
// interpolate_2D_2D_cpp
NumericMatrix interpolate_2D_2D_cpp(NumericVector input_x, NumericVector input_y, NumericMatrix input_2D, NumericVector output_x, NumericVector output_y, double asp);
RcppExport SEXP _dtRtools_interpolate_2D_2D_cpp(SEXP input_xSEXP, SEXP input_ySEXP, SEXP input_2DSEXP, SEXP output_xSEXP, SEXP output_ySEXP, SEXP aspSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type input_x(input_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type input_y(input_ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type input_2D(input_2DSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type output_x(output_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type output_y(output_ySEXP);
    Rcpp::traits::input_parameter< double >::type asp(aspSEXP);
    rcpp_result_gen = Rcpp::wrap(interpolate_2D_2D_cpp(input_x, input_y, input_2D, output_x, output_y, asp));
    return rcpp_result_gen;
END_RCPP
}
// interpolate_2D_2D_r_cpp
NumericMatrix interpolate_2D_2D_r_cpp(NumericVector range_x, NumericVector range_y, NumericMatrix input_2D, NumericVector output_x, NumericVector output_y, double asp);
RcppExport SEXP _dtRtools_interpolate_2D_2D_r_cpp(SEXP range_xSEXP, SEXP range_ySEXP, SEXP input_2DSEXP, SEXP output_xSEXP, SEXP output_ySEXP, SEXP aspSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type range_x(range_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type range_y(range_ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type input_2D(input_2DSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type output_x(output_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type output_y(output_ySEXP);
    Rcpp::traits::input_parameter< double >::type asp(aspSEXP);
    rcpp_result_gen = Rcpp::wrap(interpolate_2D_2D_r_cpp(range_x, range_y, input_2D, output_x, output_y, asp));
    return rcpp_result_gen;
END_RCPP
}
// interpolate_xy_xy_cpp
NumericVector interpolate_xy_xy_cpp(NumericMatrix input_xyv, NumericMatrix output_xy, int nmean, double asp);
RcppExport SEXP _dtRtools_interpolate_xy_xy_cpp(SEXP input_xyvSEXP, SEXP output_xySEXP, SEXP nmeanSEXP, SEXP aspSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type input_xyv(input_xyvSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type output_xy(output_xySEXP);
    Rcpp::traits::input_parameter< int >::type nmean(nmeanSEXP);
    Rcpp::traits::input_parameter< double >::type asp(aspSEXP);
    rcpp_result_gen = Rcpp::wrap(interpolate_xy_xy_cpp(input_xyv, output_xy, nmean, asp));
    return rcpp_result_gen;
END_RCPP
}
// interpolate_ts_cpp
NumericMatrix interpolate_ts_cpp(NumericMatrix input_xy, NumericMatrix input_t, NumericMatrix output_xy, int nmean, double asp);
RcppExport SEXP _dtRtools_interpolate_ts_cpp(SEXP input_xySEXP, SEXP input_tSEXP, SEXP output_xySEXP, SEXP nmeanSEXP, SEXP aspSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type input_xy(input_xySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type input_t(input_tSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type output_xy(output_xySEXP);
    Rcpp::traits::input_parameter< int >::type nmean(nmeanSEXP);
    Rcpp::traits::input_parameter< double >::type asp(aspSEXP);
    rcpp_result_gen = Rcpp::wrap(interpolate_ts_cpp(input_xy, input_t, output_xy, nmean, asp));
    return rcpp_result_gen;
END_RCPP
}
// interpolate_ts_xy_2D_cpp
NumericMatrix interpolate_ts_xy_2D_cpp(NumericMatrix input_xy, NumericMatrix input_t, NumericVector output_x, NumericVector output_y, int nmean, double asp);
RcppExport SEXP _dtRtools_interpolate_ts_xy_2D_cpp(SEXP input_xySEXP, SEXP input_tSEXP, SEXP output_xSEXP, SEXP output_ySEXP, SEXP nmeanSEXP, SEXP aspSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type input_xy(input_xySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type input_t(input_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type output_x(output_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type output_y(output_ySEXP);
    Rcpp::traits::input_parameter< int >::type nmean(nmeanSEXP);
    Rcpp::traits::input_parameter< double >::type asp(aspSEXP);
    rcpp_result_gen = Rcpp::wrap(interpolate_ts_xy_2D_cpp(input_xy, input_t, output_x, output_y, nmean, asp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dtRtools_average_xy_2D_r_cpp", (DL_FUNC) &_dtRtools_average_xy_2D_r_cpp, 3},
    {"_dtRtools_average_2D_2D_r_cpp", (DL_FUNC) &_dtRtools_average_2D_2D_r_cpp, 5},
    {"_dtRtools_average_grid_t", (DL_FUNC) &_dtRtools_average_grid_t, 7},
    {"_dtRtools_interpolate_2D_xy_cpp", (DL_FUNC) &_dtRtools_interpolate_2D_xy_cpp, 5},
    {"_dtRtools_interpolate_2D_xy_r_cpp", (DL_FUNC) &_dtRtools_interpolate_2D_xy_r_cpp, 5},
    {"_dtRtools_interpolate_xy_2D_cpp", (DL_FUNC) &_dtRtools_interpolate_xy_2D_cpp, 5},
    {"_dtRtools_interpolate_2D_2D_cpp", (DL_FUNC) &_dtRtools_interpolate_2D_2D_cpp, 6},
    {"_dtRtools_interpolate_2D_2D_r_cpp", (DL_FUNC) &_dtRtools_interpolate_2D_2D_r_cpp, 6},
    {"_dtRtools_interpolate_xy_xy_cpp", (DL_FUNC) &_dtRtools_interpolate_xy_xy_cpp, 4},
    {"_dtRtools_interpolate_ts_cpp", (DL_FUNC) &_dtRtools_interpolate_ts_cpp, 5},
    {"_dtRtools_interpolate_ts_xy_2D_cpp", (DL_FUNC) &_dtRtools_interpolate_ts_xy_2D_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_dtRtools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
