# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

average_grid_t <- function(in_xy2D, in_t, xyout, range_x, range_y, out_t) {
    .Call(`_dtTools_average_grid_t`, in_xy2D, in_t, xyout, range_x, range_y, out_t)
}

intPP_mixed <- function(zmax, kd, par, alfa, eopt, pmax, height) {
    .Call(`_dtTools_intPP_mixed`, zmax, kd, par, alfa, eopt, pmax, height)
}

rad_bot <- function(zmax, kd, par, height) {
    .Call(`_dtTools_rad_bot`, zmax, kd, par, height)
}

intPP_exp <- function(zmax, kd, pMud, par, alfa, eopt, pmax) {
    .Call(`_dtTools_intPP_exp`, zmax, kd, pMud, par, alfa, eopt, pmax)
}

